---
language: python
services: docker

env:
  global:
    - ROLE_NAME: patroni
  matrix:
    - MOLECULE_DISTRO: centos7

install:
  # Install test dependencies.
  - pip3 install --upgrade pip
  - pip3 install molecule yamllint ansible-lint docker
  - pip install psycopg2 psycopg2-binary

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME yanehi.$ROLE_NAME
  - cd yanehi.$ROLE_NAME

script:
  # Run tests.
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python get-pip.py
  - python3 get-pip.py
  - which pip3
  - which pip
  - pip --version
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
