---
language: python
services: docker

env:
  global:
    - ROLE_NAME: patroni
  matrix:
    - MOLECULE_DISTRO: centos7
  
before_install:
  # upgrade pip
  - python3 -m pip install --upgrade pip
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python get-pip.py
  - which pip3

install:
  # Install test dependencies.
  - pip3 install --upgrade pip
  - pip3 install molecule yamllint ansible-lint docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME yanehi.$ROLE_NAME
  - cd yanehi.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
