---
language: python
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
services: docker

env:
  global:
    - ROLE_NAME: patroni
  matrix:
    - MOLECULE_DISTRO: centos7
    
# before_install:
  # upgrade pip
#  - python -m pip install --upgrade pip
 
install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME yanehi.$ROLE_NAME
  - cd yanehi.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
