# https://github.com/geerlingguy/ansible-role-repo-epel
- name: Check if EPEL repo is already configured.
  stat:
    path: /etc/yum.repos.d/epel.repo
  register: epel_repofile_result

- name: install epel repo
  command: yum install epel-release -y

- name: Exclude CentOS PostgreSQL packages
  ini_file:
    path: /etc/yum.repos.d/CentOS-Base.repo
    option: exclude
    value: postgresql*
    section: "{{ item }}"
  with_items:
    - base
    - updates

- name: Add Yum repository
  yum:
    name: "{{ pg_repo_url }}"
    state: present
