---
#- name: firewall rules for postgres, patroni and etcd
#  command: echo "net.ipv4.ip_nonlocal_bind = 1" >> /etc/sysctl.conf; echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf; sysctl -p

- name: udp etcd connection port for etcd
  firewalld:
    port: "{{ etcd_port }}/udp"
    permanent: yes
    immediate: yes
    zone: public
    state: enabled

- name: tcp etcd connection port for etcd
  firewalld:
    port: "{{ etcd_port }}/tcp"
    permanent: yes
    immediate: yes
    zone: public
    state: enabled

- name: postgresql server port
  firewalld:
    port: "{{ pg_port }}/tcp"
    permanent: yes
    immediate: yes
    zone: public
    state: enabled

- name: patroni port
  firewalld:
    port: "{{ patroni_port }}/tcp"
    permanent: yes
    immediate: yes
    zone: public
    state: enabled

- name: dhcp reserved port
  firewalld:
    port: 67/tcp
    permanent: yes
    immediate: yes
    zone: public
    state: enabled

- name: dhcp reserved port
  firewalld:
    port: 68/tcp
    permanent: yes
    immediate: yes
    zone: public
    state: enabled

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded